### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by felixboehm** [owncloud/market#100]
# development
- [x] merge open PRs for release @felixheidecke 

# qa 
- [x] testing the market app @hurradieweltgehtunter @felixheidecke 

# release
- [ ] build, sign @DeepDiver1975 
- [ ] upload to marketplace @DeepDiver1975

**Comment by hurradieweltgehtunter** [comment]
also see here for todo's: https://github.com/owncloud/market/issues/96

**Comment by hurradieweltgehtunter** [comment]
continued in #96 - double issue
