### ISSUE TITLE
0.2.3 release checklist

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/market#190]
**Reason**
- Show more detailed update information - [#159](https://github.com/owncloud/market/pull/159)
- Darken card box-shadow - [#136](https://github.com/owncloud/market/issues/136)
- Handle cluster setups better - [#125](https://github.com/owncloud/market/issues/125) [#184](https://github.com/owncloud/market/pull/184)

**QA**
- [x] Create release branch (@patrickjahns)
- [x] Create "0.2.3 Testplan" https://github.com/owncloud/market/issues/192
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

**Marketing**
- [x] Check/adapt info.xml stuff
- [x] Check/adapt screenshot
- [x] Blog post or other communication if applicable

**Documentation**
- [x] Changes in the docs needed?

**Build & Marketplace release**

- [x] Bump version in info.xml 
- [x] Update CHANGELOG.md (@patrickjahns)
- [x] Sign and build tarball  (@patrickjahns)
- [x] Upload to marketplace  (@patrickjahns)
- [x] Rename QA milestone to '$version'  (@patrickjahns)
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section (@patrickjahns)
- [x] create PR for `master` to bring back changes from release branch #195

**Comment by patrickjahns** [comment]
@felixheidecke @PVince81 
do we need to create a PR to document the cluster setup flag?

**Comment by patrickjahns** [comment]
@pmaier1 
released - close as you see fit

**Comment by pmaier1** [comment]
No explicit communication or doc changes needed IMO. Closing. Thanks!
