### ISSUE TITLE
0.2.4 release checklist

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/market#316]
# App release template

### Reason
- release needed for #282 

### QA
- [x] Create release branch @patrickjahns https://github.com/owncloud/market/tree/release/0.2.4
- [x] Create "$version Testplan"  @voroyam https://github.com/owncloud/market/issues/319
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Marketing
- [x] Ping RocketChat channel #marketing  @patrickjahns
- ~~Check/adapt info.xml stuff~~
- ~~Check/adapt screenshot~~
- ~~Blog post or other communication if applicable~~

### Documentation
- [ ] Changes in the docs needed? -> @voroyam can you document for the appliance that clearing the cache helps with enterprise trail

### Build & Marketplace release

- [x] Bump version in info.xml  @patrickjahns
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version'  @patrickjahns
- [x] Create github tag for '$version'  @patrickjahns
- [x] Build and sign tarball from github tag '$version'  @patrickjahns
- [x] Upload to marketplace  @patrickjahns
- [ ] Send mail to release-coordination with link to this ticket and to the changelog  
- [x] Rename QA milestone to '$version'  @patrickjahns
- [ ] Add a new 'Unreleased' section in CHANGELOG.md  @patrickjahns
- [x] Create PR to merge changes back to `master`  @patrickjahns https://github.com/owncloud/market/pull/318

**Comment by patrickjahns** [comment]
Pre-release tarball https://cloud.owncloud.com/index.php/s/j9RNopDmPZScJ1g - not it is **not signed**
