### ISSUE TITLE
Tracking testing results for market 0.4.0

### ISSUE THREAD

**Issue by davitol** [owncloud/market#455]
Tests using tarball provided by development.

| Test Case                                | Expected Result                           | Result 10.0.10 | Result 10.1 | Related Comment |
| ---------------------------------------- | ----------------------------------------  | --------------- | --------------- | --------------- |
| Enable market app. Login as admin user and regular user. | Admin user can see cart icon in the left menu and can be accessed. Regular user cannot see cart icon and cannot access market. | ✅   |✅  |                 |
| Check that left and right menus are following the css style of the rest of oC server  |   | ✅  |  ✅  |          |
| Check that the connection with the marketplace is working and the list of apps is being retrieved. |                                           |✅ | ✅   |                 |
| Install one community app previously included with owncloud. (user_ldap, activity,  gallery, etc) | There is no problem with installation. (If there are problems try with another, here we are testing the market app, not the actual app installed)  | ✅  |✅   |                 |
| Follow the enterprise trial process to convert a community edition server into an enterprise edition one. https://marketplace.owncloud.com/enterprise-trial | The process is smooth and as result you get a working EE instance. | ✅  |✅  |                 |
| Use occ market:list                      | A list of the existing apps in the marketplace appears.  |✅  |✅  |                 |
| Use occ market:install {choose an app from the previous list} | The app is installed correctly.          | ✅  |✅  |                 |
| 1. Download the code from marketplace of an app of your choice like a tar.gz file. 2. Use occ market:install --local=AppCode.tar.gz | The app is installed correctly.           |✅  | ✅  |                 |
| 1. Download the code from marketplace of an app of your choice with several versions available like a tar.gz file, get the oldest version available. Also download the newest version. 2. Use occ market:install --local=App.oldVersion.tar.gz 3. Run occ market:upgrade --local=App.newVersion.tar.gz | The app is updated correctly.           | ✅  |✅ |                 |
| Check that the web ui elements work fine using Safari |                                          |✅  |✅  |                 |
| Check that the web ui elements work fine using IE 11 |                                           | ✅  |✅  |                 |
| Check that the web ui elements work fine using Edge |                                           | ✅  |✅  |                 |
| Check that the web ui elements work fine using Firefox |                                          | ✅  |✅ |                 |
| Check that the web ui elements work fine using Chrome |                                          | ✅  |✅  |                 |
| Having installed one app from the marketplace, uninstall it using the webui, reinstall it again |  The app is uninstalled correctly and installed again without problems.                                          | ✅  |✅  |                 |

**Comment by davitol** [comment]
## Changelog

Added

- [ ] Login directly from market-app to auto-install api-key - #443

Changed

- [ ] Bump npm-watch from 0.1.9 to 0.5.0 - #429
- [ ] Bump vue-router from 2.7.0 to 3.0.2 - #431
- [ ] Bump vue-gettext from 2.0.23 to 2.1.2 - #440
- [ ] Bump vue and vue-template-compiler - #428
- [ ] Bump uikit from 3.0.0-beta.34 to 3.0.0-rc.26 - #441
- [ ] Bump uglify-js from 3.1.3 to 3.4.9 - #394
- [ ] Library updates to resolve vulnerabilities - #377 #445

Fixed

 - [ ] Hide api key in xhr-responses if key is configured in config.php - #454
 - [ ]  Hide 'Edit/Add API Key' button if not changeable - #185
 - [ ]  Fix "Logged In" is shown despite being logged out - #450
 - [ ]  Fix typo "Logged In" - #448
 - [ ]  Prevent uninstalling market app from within market app - #145
