### ISSUE TITLE
Tracking Testing results for Market 0.6.0

### ISSUE THREAD

**Issue by davitol** [owncloud/market#577]
Test Plan Results:

Tests using tarball provided by development.

| Test Case                                | Expected Result                            | Result 10.5| Related Comment |
| ---------------------------------------- | ----------------------------------------  | --------------- | --------------- | --------------- |
| Enable market app. Login as admin user and regular user. | Admin user can see cart icon in the left menu and can be accessed. Regular user cannot see cart icon and cannot access market.    |✅  |                 |
| Check that left and right menus are following the css style of the rest of oC server  |    |  ✅  |          |
| Check that the connection with the marketplace is working and the list of apps is being retrieved. |                                            | ✅   |                 |
| Install one community app previously included with owncloud. (user_ldap, activity,  gallery, etc) | There is no problem with installation. (If there are problems try with another, here we are testing the market app, not the actual app installed)    |✅   |                 |
| Follow the enterprise trial process to convert a community edition server into an enterprise edition one. https://marketplace.owncloud.com/enterprise-trial | The process is smooth and as result you get a working EE instance.   |NA |                 |
| Use occ market:list                      | A list of the existing apps in the marketplace appears.   |✅  |                 |
| Use occ market:install {choose an app from the previous list} | The app is installed correctly.          |  |✅  |                 |
| 1. Download the code from marketplace of an app of your choice like a tar.gz file. 2. Use occ market:install --local=AppCode.tar.gz | The app is installed correctly.            | ✅  |                 |
| 1. Download the code from marketplace of an app of your choice with several versions available like a tar.gz file, get the oldest version available. Also download the newest version. 2. Use occ market:install --local=App.oldVersion.tar.gz 3. Run occ market:upgrade --local=App.newVersion.tar.gz | The app is updated correctly.             |✅ |                 |
| Check that the web ui elements work fine using Safari |                                           |✅  |                 |
| Check that the web ui elements work fine using Edge |                                             |✅  |                 |
| Check that the web ui elements work fine using Firefox |                                           |✅ |                 |
| Check that the web ui elements work fine using Chrome |                                         |✅  |                 |
| Having installed one app from the marketplace, uninstall it using the webui, reinstall it again |  The app is uninstalled correctly and installed again without problems.                                          |✅  |                 |

**Comment by davitol** [comment]
## [0.6.0] - 2020-06-23

### Removed

- [ ] Drop login button - [#573](https://github.com/owncloud/market/issues/573)
- [ ] Drop start trial functionality - [#572](https://github.com/owncloud/market/issues/572)

### Changed

- [ ] Bump libraries

**Comment by davitol** [comment]
## Issues found during QA:

- [ ] https://github.com/owncloud/market/issues/574#issuecomment-651592814
- [ ] https://github.com/owncloud/market/issues/574#issuecomment-651633421
- [ ] Translations missed in tarball (included in master branch) https://github.com/owncloud/market/issues/574#issuecomment-648619761
